<?php


namespace Isofman\LaravelUtilities\Eloquent;

use \Illuminate\Database\Eloquent\Builder as EloquentBuilder;

class Builder extends EloquentBuilder
{
    public function firstSafe($columns = ['*'])
    {
        $item = $this->first($columns);

        if($item) {
            return $item;
        }

        return new NullModel;
    }

    public function firstOrFail($columns = ['*'])
    {
        return parent::firstOrFail($columns); // TODO: Change the autogenerated stub
    }
}